name: Build Image and Push Registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t portfolio .

      - name: Log in to Docker Registry
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        run: echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY_NAME} -u ${REGISTRY_USERNAME} --password-stdin
      
      - name: Push Docker Image
        env:  
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        run: docker push ${REGISTRY_NAME}/portfolio
  