name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Image and Push Registry"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_USER: ${{secrets.VPS_USER}}
      VPS_IP: ${{secrets.VPS_IP}}
      VPS_SSH_KEY: ${{secrets.VPS_SSH_KEY}}
      REGISTRY_NAME: ${{secrets.REGISTRY_NAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup SSH for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.VPS_SSH_KEY}}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: SSH into VPS and deploy  
        run: |
          ssh $VPS_USER@$VPS_IP << EOF
            echo "--Start Pulling image--"
            sudo docker pull $REGISTRY_NAME/portfolio
            echo "--End Pulling image--"
            sudo docker stop portfolio-container || true
            sudo docker rm portfolio-container || true
            echo "--Running container--"
            sudo docker run -p 3000:80 --name portfolio-container -d $REGISTRY_NAME/portfolio
          EOF
